;
; File generated by cc65 v 2.17 - Git N/A
;
	.fopt		compiler,"cc65 v 2.17 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_cputsxy
	.export		_main

.segment	"RODATA"

L0006:
	.byte	$48,$65,$6C,$6C,$6F,$00

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int, __near__ __near__ unsigned char * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$0A                 ; USE: ___________  CHG: __A________  SIZE: 2    In A:XX X:XX Y:XX  Out A:0A X:XX Y:XX
	jsr     pusha                ; USE: __A________  CHG: ____Y______  SIZE: 3    In A:0A X:XX Y:XX  Out A:0A X:XX Y:XX
	jsr     pusha                ; USE: __A________  CHG: ____Y______  SIZE: 3    In A:0A X:XX Y:XX  Out A:0A X:XX Y:XX
	lda     #<(L0006)            ; USE: ___________  CHG: __A________  SIZE: 2    In A:0A X:XX Y:XX  Out A:XX X:XX Y:XX
	ldx     #>(L0006)            ; USE: ___________  CHG: ___X_______  SIZE: 2    In A:XX X:XX Y:XX  Out A:XX X:XX Y:XX
	jsr     _cputsxy             ; USE: __AX_______  CHG: HLAXYT112VS  SIZE: 3    In A:XX X:XX Y:XX  Out A:XX X:XX Y:XX
L000A:	jmp     L000A                ; USE: ___________  CHG: ___________  SIZE: 3    In A:XX X:XX Y:XX  Out A:XX X:XX Y:XX

.endproc

