#!/usr/bin/bash
URL="http://localhost:8082/wordpress/wp_posts/post" 
DATA=@./src/a.html
HEADER=
CURL=/usr/bin/curl
#curl -X POST "http://localhost:8082/wordpress/wp_posts/post" -H  "accept: application/json"
$CURL \
	$URL \
	-X POST \
	--data $DATA \
	-H  "accept: application/json" \
	-H  "title: curl000" \
	-H  "status: publish" \
	-H  "image: mendix.png" \
	-H  "type: Post"  > ./response
cat ./response
